# EDW系统主配置文件
# 修改此文件后需要重启系统或使用 /config reload 命令

# MCP服务器配置
mcp_servers:
  databricks:
    url: "http://127.0.0.1:8000/sse"
    transport: "sse"
    env:
      DATABRICKS_HOST: ""  # 从环境变量 DATABRICKS_HOST 获取
      DATABRICKS_TOKEN: "" # 从环境变量 DATABRICKS_TOKEN 获取

# 缓存配置
cache:
  ttl_seconds: 3600        # 缓存生存时间（秒），默认1小时
  max_entries: 1000        # 最大缓存条目数
  cleanup_interval: 300    # 清理间隔（秒），默认5分钟
  enabled: true            # 是否启用缓存

# 验证配置
validation:
  similarity_threshold: 0.6     # 字段相似度阈值
  max_suggestions: 5           # 最大建议字段数
  enable_pattern_matching: true # 启用模式匹配

# 系统配置
system:
  log_level: INFO              # 日志级别：DEBUG, INFO, WARNING, ERROR
  thread_id_length: 16         # 线程ID长度
  max_retry_attempts: 3        # 最大重试次数
  request_timeout: 120         # 请求超时时间（秒）

# 消息管理配置
message_management:
  summary_enabled: true        # 是否启用自动消息总结
  summary_threshold: 20        # 触发总结的消息数量阈值
  keep_recent_count: 5         # 总结后保留的最近消息数
  max_context_length: 10       # 意图分析时的最大上下文消息数